export const ExampleData2 = [
   {
      name: "Reporte de la semana 2023-10-08 al 2023-10-14",
      mostTicketsClassroom: [
         {
            _id: ["Toluca"],
            count: 1,
         },
      ],
      leastTicketsClassroom: [
         {
            _id: ["Santa Fe"],
            count: 1,
         },
      ],
      avgClosureTime: null,
      activeTickets: [
         {
            _id: "651f46937041df7c475efcd2",
            title: "Tara big zone YES",
            categoryId: "digital",
            subcategoryIndex: 4,
            priority: 2,
            status: 1,
            description: "My boy is just really massive u know wham saying?",
            createdAt: "2023-10-05T23:28:19.108Z",
            id: 2,
            closedAt: "2023-10-05T23:28:54.305Z",
            assignee: "Rodrigo",
            classroomId: 2,
         },
         {
            _id: "65249d6813eaeb0cb74cc1fb",
            title: "Test_public",
            assignee: "Wesh",
            categoryId: "digital",
            subcategoryIndex: 3,
            priority: 2,
            status: 1,
            description: "Lorem ipsum dolor sit amet, et consecetur",
            createdAt: "2023-10-10T00:40:08.569Z",
            id: 6,
            reportedBy: "Fuego",
            classroomId: 3,
         },
      ],
      newTickets: [
         {
            _id: 1,
            count: 1,
         },
         {
            _id: 0,
            count: 5,
         },
      ],
      closedTickets: [
         {
            _id: 2,
            count: 1,
         },
      ],
      id: 1,
   },
   {
      name: "Reporte de la semana 2023-10-15 al 2023-10-21",
      mostTicketsClassroom: [],
      leastTicketsClassroom: [],
      avgClosureTime: null,
      activeTickets: [],
      newTickets: [],
      closedTickets: [],
      id: 2,
      wasUpdated: "2023-10-17T23:51:01.767Z",
      updated: "2023-10-18T00:28:46.506Z",
   },
   {
      name: "Reporte de la semana 2023-10-08 al 2023-10-14",
      mostTicketsClassroom: [
         {
            _id: ["Toluca"],
            count: 1,
         },
      ],
      leastTicketsClassroom: [
         {
            _id: ["Santa Fe"],
            count: 1,
         },
      ],
      avgClosureTime: null,
      activeTickets: [
         {
            _id: "651f46937041df7c475efcd2",
            title: "Tara big zone YES",
            categoryId: "digital",
            subcategoryIndex: 4,
            priority: 2,
            status: 1,
            description: "My boy is just really massive u know wham saying?",
            createdAt: "2023-10-05T23:28:19.108Z",
            id: 2,
            closedAt: "2023-10-05T23:28:54.305Z",
            assignee: "Rodrigo",
            classroomId: 2,
         },
         {
            _id: "65249d6813eaeb0cb74cc1fb",
            title: "Test_public",
            assignee: "Wesh",
            categoryId: "digital",
            subcategoryIndex: 3,
            priority: 2,
            status: 1,
            description: "Lorem ipsum dolor sit amet, et consecetur",
            createdAt: "2023-10-10T00:40:08.569Z",
            id: 6,
            reportedBy: "Fuego",
            classroomId: 3,
         },
      ],
      newTickets: [
         {
            _id: 1,
            count: 1,
         },
         {
            _id: 0,
            count: 5,
         },
      ],
      closedTickets: [
         {
            _id: 2,
            count: 1,
         },
      ],
      id: 1,
   },
   {
      name: "Reporte de la semana 2023-10-15 al 2023-10-21",
      mostTicketsClassroom: [],
      leastTicketsClassroom: [],
      avgClosureTime: null,
      activeTickets: [],
      newTickets: [],
      closedTickets: [],
      id: 2,
      wasUpdated: "2023-10-17T23:51:01.767Z",
      updated: "2023-10-18T00:28:46.506Z",
   },
   {
      name: "Reporte de la semana 2023-10-22 al 2023-10-14",
      mostTicketsClassroom: [
         {
            _id: ["Toluca"],
            count: 1,
         },
      ],
      leastTicketsClassroom: [
         {
            _id: ["Santa Fe"],
            count: 1,
         },
      ],
      avgClosureTime: null,
      activeTickets: [
         {
            _id: "651f46937041df7c475efcd2",
            title: "Tara big zone YES",
            categoryId: "digital",
            subcategoryIndex: 4,
            priority: 2,
            status: 1,
            description: "My boy is just really massive u know wham saying?",
            createdAt: "2023-10-05T23:28:19.108Z",
            id: 2,
            closedAt: "2023-10-05T23:28:54.305Z",
            assignee: "Rodrigo",
            classroomId: 2,
         },
         {
            _id: "65249d6813eaeb0cb74cc1fb",
            title: "Test_public",
            assignee: "Wesh",
            categoryId: "digital",
            subcategoryIndex: 3,
            priority: 2,
            status: 1,
            description: "Lorem ipsum dolor sit amet, et consecetur",
            createdAt: "2023-10-10T00:40:08.569Z",
            id: 6,
            reportedBy: "Fuego",
            classroomId: 3,
         },
      ],
      newTickets: [
         {
            _id: 1,
            count: 1,
         },
         {
            _id: 0,
            count: 5,
         },
      ],
      closedTickets: [
         {
            _id: 2,
            count: 1,
         },
      ],
      id: 1,
   },
   {
      name: "Reporte de la semana 2023-10-15 al 2023-10-21",
      mostTicketsClassroom: [],
      leastTicketsClassroom: [],
      avgClosureTime: null,
      activeTickets: [],
      newTickets: [],
      closedTickets: [],
      id: 2,
      wasUpdated: "2023-10-17T23:51:01.767Z",
      updated: "2023-10-18T00:28:46.506Z",
   },
]
